{
  lib,
  pkgs,
  ...
}:
{
  config = lib.mkIf pkgs.stdenv.isDarwin {
    home.file = {
      ".config/karabiner/karabiner.json" = {
        force = true;
        text = builtins.toJSON {
          profiles = [
            {
              name = "Default";
              selected = true;
              virtual_hid_keyboard = {
                keyboard_type_v2 = "ansi";
              };
              complex_modifications = {
                rules = [
                  {
                    description = "Remap Cmd+Tab to F18 for AeroSpace";
                    manipulators = [
                      {
                        type = "basic";
                        from = {
                          key_code = "tab";
                          modifiers = {
                            mandatory = [ "command" ];
                            optional = [ "caps_lock" ];
                          };
                        };
                        to = [
                          { key_code = "f18"; }
                        ];
                      }
                    ];
                  }
                  {
                    description = "Remap Cmd+Shift+Tab to F19 for AeroSpace";
                    manipulators = [
                      {
                        type = "basic";
                        from = {
                          key_code = "tab";
                          modifiers = {
                            mandatory = [
                              "command"
                              "shift"
                            ];
                            optional = [ "caps_lock" ];
                          };
                        };
                        to = [
                          { key_code = "f19"; }
                        ];
                      }
                    ];
                  }
                  {
                    description = "Remap Cmd+Enter to F17 for AeroSpace";
                    # AeroSpace must bind F17 instead of Cmd+Enter, otherwise it
                    # would also swallow the synthetic Cmd+Enter generated by the
                    # Ctrl+Enter remap below before it reaches apps like Slack.
                    manipulators = [
                      {
                        type = "basic";
                        from = {
                          key_code = "return_or_enter";
                          modifiers = {
                            mandatory = [ "command" ];
                            optional = [ "caps_lock" ];
                          };
                        };
                        to = [
                          { key_code = "f17"; }
                        ];
                      }
                    ];
                  }
                  {
                    description = ''
                      Remap Ctrl+A/C/V/X/Z(+Shift)/Enter to Cmd equivalents except in terminal apps
                    '';
                    manipulators =
                      let
                        # WezTerm and Terminal.app are excluded so Ctrl+A/C/V/X/Z still behave as expected in a shell.
                        terminalApps = [
                          "^com\\.github\\.wez\\.wezterm$"
                          "^com\\.apple\\.Terminal$"
                        ];
                        remap = key: extraModifiers: {
                          type = "basic";
                          from = {
                            key_code = key;
                            modifiers = {
                              mandatory = [ "control" ] ++ extraModifiers;
                              optional = [ "caps_lock" ];
                            };
                          };
                          to = [
                            {
                              key_code = key;
                              modifiers = [ "command" ] ++ extraModifiers;
                            }
                          ];
                          conditions = [
                            {
                              type = "frontmost_application_unless";
                              bundle_identifiers = terminalApps;
                            }
                          ];
                        };
                      in
                      [
                        (remap "a" [ ])
                        (remap "c" [ ])
                        (remap "v" [ ])
                        (remap "x" [ ])
                        (remap "z" [ ])
                        (remap "c" [ "shift" ])
                        (remap "v" [ "shift" ])
                        (remap "z" [ "shift" ])
                        (remap "return_or_enter" [ ])
                      ];
                  }
                ];
              };
            }
          ];
        };
      };
    };
  };
}
